name: Build Multi Platform Docker Image

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      build_arm64:
        description: 'Build ARM64 image'
        required: false
        default: 'false'
  push:
    branches:
      - main

env:
  REGISTRY_HOST: registry.cn-hangzhou.aliyuncs.com
  CONTAINER_NAME: apm-adapter
  DEPLOYMENT_NAME: apm-adapter
  NAMESPACE: apo

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG_NAME: ${{ steps.build-image.outputs.IMAGE_TAG_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca



      - name: Generate image metadata
        id: build-image
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          DATE=$(date +"%Y%m%d%H%M%S%Z")
          BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's#[^a-zA-Z0-9._-]#-#g')
          IMAGE_TAG_NAME="${BRANCH_NAME}-${COMMIT_HASH::7}-${DATE}"
          echo "IMAGE_TAG_NAME=$IMAGE_TAG_NAME" >> "$GITHUB_OUTPUT"
          echo "IMAGE_FULL_TAG_AMD64=${{ env.REGISTRY_HOST }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.CONTAINER_NAME }}:${IMAGE_TAG_NAME}" >> $GITHUB_ENV  
          echo "IMAGE_FULL_TAG_ARM64=${{ env.REGISTRY_HOST }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.CONTAINER_NAME }}:${IMAGE_TAG_NAME}-arm64" >> $GITHUB_ENV

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: ${{ env.IMAGE_FULL_TAG_AMD64 }}

      - name: Build and push ARM64 image
        if: ${{ github.event.inputs.build_arm64 == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: false
          tags: ${{ env.IMAGE_FULL_TAG_ARM64 }}
